//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagement_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BillID { get; set; }
        public Nullable<int> ReadingID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public decimal UnitsConsumed { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual Reading Reading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
