//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagement_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tariff()
        {
            this.TariffSlabs = new HashSet<TariffSlab>();
        }
    
        public int TariffID { get; set; }
        public Nullable<int> UtilityID { get; set; }
        public string TariffName { get; set; }
        public decimal UnitRate { get; set; }
        public Nullable<decimal> FixedCharge { get; set; }
    
        public virtual UtilityType UtilityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TariffSlab> TariffSlabs { get; set; }
    }
}
