//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagement_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffSlab
    {
        public int SlabID { get; set; }
        public Nullable<int> TariffID { get; set; }
        public Nullable<decimal> FromUnit { get; set; }
        public Nullable<decimal> ToUnit { get; set; }
        public decimal RatePerUnit { get; set; }
    
        public virtual Tariff Tariff { get; set; }
    }
}
