//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagement_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UMS_DBEntities : DbContext
    {
        public UMS_DBEntities()
            : base("name=UMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Meter> Meters { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Premis> Premises { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
        public virtual DbSet<TariffSlab> TariffSlabs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UtilityType> UtilityTypes { get; set; }
        public virtual DbSet<v_MonthlyRevenue> v_MonthlyRevenue { get; set; }
        public virtual DbSet<v_TopConsumers> v_TopConsumers { get; set; }
        public virtual DbSet<v_UnpaidBillsReport> v_UnpaidBillsReport { get; set; }
    
        public virtual int sp_RegisterNewCustomer(string fullName, string email, string phone, string address)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegisterNewCustomer", fullNameParameter, emailParameter, phoneParameter, addressParameter);
        }
    
        public virtual int sp_SubmitReadingAndGenerateBill(Nullable<int> meterID, Nullable<decimal> currentReading, Nullable<System.DateTime> readingDate)
        {
            var meterIDParameter = meterID.HasValue ?
                new ObjectParameter("MeterID", meterID) :
                new ObjectParameter("MeterID", typeof(int));
    
            var currentReadingParameter = currentReading.HasValue ?
                new ObjectParameter("CurrentReading", currentReading) :
                new ObjectParameter("CurrentReading", typeof(decimal));
    
            var readingDateParameter = readingDate.HasValue ?
                new ObjectParameter("ReadingDate", readingDate) :
                new ObjectParameter("ReadingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SubmitReadingAndGenerateBill", meterIDParameter, currentReadingParameter, readingDateParameter);
        }
    }
}
