//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagement_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TopConsumers
    {
        public string FullName { get; set; }
        public string Utility { get; set; }
        public Nullable<decimal> TotalUsage { get; set; }
        public Nullable<decimal> TotalSpent { get; set; }
    }
}
